### ISSUE TITLE
路由进不去 robot 页面，一直在 app#/intro 授权

### ISSUE THREAD

**Issue by scarletfrank** [WecomTeam/CodeSameples#10]
## 我的步骤
1. 测试号搞了个`webbook`填入`robot_webhook`
2. 测试号抄来`corp_id` `agent_id` `app_secret`
3. 修改本地host + 在应用的“企业微信授权登录”配置加上 `myapp.com:3000`
4. `npm start` ,
5. 我访问 `http://myapp.com:3000/#/intro`
6. 扫码之后，跳转到 `http://myapp.com:3000/app#/intro`，如下面的图一
7.再扫一次，还是一样的路径，一样的页面，又提示我扫码

## 我的问题

我该怎么做才能看到图二，是我少改了哪里的配置吗？
还是说本项目代码做过更改，我看的资料过时了（因为路径和端口也不太一样了）

## 图片

- 图片一
![image](https://camo.githubusercontent.com/b58e8d4678ca572e859e1bc61583f1ac282f5fca2a55aa5c26ac3e1cf633653b/68747470733a2f2f77646f632d37363439312e706963677a632e717069632e636e2f4d5459344f4467314d5451784f4449344d7a59354d775f3639383836365f783437746159536c697363316e7365335f313635343133393133313f773d3132383026683d3935382e38343035373937313031343439)

- 图片二
![image](https://user-images.githubusercontent.com/25702099/187859395-27e029a7-ed23-4298-84e6-dd5ee3264ff0.png)

## 其他资料

1. 我看企业微信开发者文档里的[开发企业微信群机器人](https://developer.work.weixin.qq.com/tutorial/detail/54)，里面说这个代码库访问` http://localhost:8080/#/robot` 有个示例页面，但我觉得我可能改下名字和端口就行，但现在问题是不停的卡在扫码授权上

2. 我是不是该看这个库啊[WecomTeam/RobotSample](https://github.com/WecomTeam/RobotSample)

**Comment by functionU** [comment]
看node打印的那个响应 里面包含了一个ip
把那个ip配置进应用的ip白名单就好

**Comment by meterscao** [comment]
看表现是因为整个项目默认进来就会检查登录态，但是机器人貌似是不需要的。
这里可以先尝试 [WecomTeam/RobotSample](https://github.com/WecomTeam/RobotSample) 这个项目，我们后续会把 CodeSample里面的机器人相关代码迁移出去。
