### ISSUE TITLE
没有办法运行

### ISSUE THREAD

**Issue by ARZhu** [WecomTeam/CodeSameples#2]
按照步骤执行下来之后，打开 http://localhost:3000/#/ 只有一个 "welcome to express" 的界面，这是为什么？

**Comment by chuyueZhang** [comment]
原工程还未被集成到node服务中，为了方便开发者使用，我们更新了部分逻辑与文档，请重新拉取项目按照文档要求执行，如果没有问题之后会将此issue关闭

**Comment by meterscao** [comment]
更新了文档和代码，原来的前端工程没有集成到node里，还是通过dev-server访问的，现在可以只开node服务了
