### ISSUE TITLE
文档学习流程建议

### ISSUE THREAD

**Issue by zhaoshiming** [WecomTeam/CodeSameples#5]
新手在看运行代码前的几个建议 
1. 管理台中新建应用的配置
   a. 应用主页配置为 http://myapp.com:3000/home
   b. 可信域名配置为 myapp.com:3000

2. 修改本地host 映射 127.0.0.1 为 myapp.com 

必须完成配置之后 代码才可正常运行

**Comment by meterscao** [comment]
感谢你的建议和补充，缺少了可信域名的配置，可能在Oauth那部分会卡住。
这部分的内容，我补充到文档中。
