### ISSUE TITLE
有自建应用代开发的demo吗？

### ISSUE THREAD

**Issue by caijohnny** [WecomTeam/CodeSameples#6]
我看这个demo是自建应用的demo，需要一个代开发的demo，
相关链接：https://work.weixin.qq.com/nl/act/p/6b9f3768a6a04fef

**Comment by meterscao** [comment]
自建代开发 、第三方应用开发 的 Demo，在准备中，近期将会推出。

**Comment by caijohnny** [comment]
大概啥时候，有个准确的时间节点吗？

**Comment by caijohnny** [comment]
@meterscao  大概什么时候呢？

**Comment by meterscao** [comment]
现在已经有了，可以关注 [代开发应用代码示例](https://github.com/WecomTeam/CustomAppCodeSample)
