### ISSUE TITLE
app请求500

### ISSUE THREAD

**Issue by qulong0908** [WecomTeam/CodeSameples#7]
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/50685016/179876507-f9b67a76-e199-4fe3-bf28-8fa8618e88ac.png">

**Comment by meterscao** [comment]
500是node抛出了异常，断点看看具体是哪里异常了

**Comment by qulong0908** [comment]
通讯录的contact_secret 我没权限 就没填，这个影响吗

**Comment by qulong0908** [comment]
> 看起来 access_token 没有获取成功

看本地搞了个缓存 去掉就行了

**Comment by meterscao** [comment]
那可能是缓存文件的读写的异常，可能是这个判断的问题

<img width="746" alt="image" src="https://user-images.githubusercontent.com/1685497/179884672-6aacf75f-c8b9-4d68-8be8-e9d6fe77f696.png">

**Comment by meterscao** [comment]
确认了是判断的问题，第一次获取access_token的时候获取失败，写入了一个错误的token，发布了一个新版本，可以更新试试
