### ISSUE TITLE
启动不起来

### ISSUE THREAD

**Issue by billypzhang** [WecomTeam/CodeSameples#8]
1、/configs/main.config.js 不存在，赋值了main.config.demo.js做了修改解决了
2、按照readme配置相关信息后，页面提示错误，如下图
![image](https://user-images.githubusercontent.com/38271770/185884856-597ae441-c437-42d1-8e5c-c1155e34a62b.png)

**Comment by meterscao** [comment]
将 main.config.demo.js 复制一份到 main.config.js 文件

注意看文件名。
