### ISSUE TITLE
使用code获取用户user_id时报错60020

### ISSUE THREAD

**Issue by Templar136** [WecomTeam/CodeSameples#9]
应用后台开启在本地127.0.0.1:3000 (myapp.com:3000)
自建应用的企业可信IP不能设置为127.0.0.1，自建应用开发阶段中也必须设置公网IP的企业可信IP吗？

**Comment by Templar136** [comment]
企业可信IP在示例的文档里并没有提到，这个新增加的企业可信IP必须是公网IP吗？

**Comment by meterscao** [comment]
文档里面有写，在最下面：
> 七、特别提示
> 从 2022.6.20 起，新建的企业内部应用，须指定企业可信IP，方可调用相关的接口，请在企业应用详情页面配置本地 IP。
> 
> 请参考[自建及代开发应用安全性升级](https://developer.work.weixin.qq.com/community/announcement/detail?content_id=16334603338859177543)。

这个IP是自己电脑的出口IP，可以直接在这里 https://www.ip138.com/ 查看

**Comment by Templar136** [comment]
清楚了，感谢
